# Generated by Django 5.2.1 on 2025-05-12 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="published",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 5, 12, 17, 57, 12, 529712, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Fecha de publicación",
            ),
        ),
    ]
