# Generated by Django 5.2.1 on 2025-05-12 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="published",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 5, 12, 18, 0, 53, 727608, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Fecha de publicación",
            ),
        ),
    ]
