# Generated by Django 5.2.1 on 2025-05-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titulo")),
                ("content", models.TextField(verbose_name="Contenido")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Edición"
                    ),
                ),
            ],
            options={
                "verbose_name": "pagina",
                "verbose_name_plural": "paginas",
                "ordering": ["title"],
            },
        ),
    ]
