# Generated by Django 5.2.1 on 2025-05-13 21:45

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_alter_page_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="content",
            field=django_quill.fields.QuillField(verbose_name="Contenido"),
        ),
    ]
