# Generated by Django 5.2.1 on 2025-05-13 21:54

import django_summernote.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_alter_page_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="content",
            field=django_summernote.fields.SummernoteTextField(
                verbose_name="Contenido"
            ),
        ),
    ]
